### ISSUE TITLE
Could not create player to play mp3 file

### ISSUE THREAD

**Issue by daniel4git** [HanSolo/SpaceFX#1]
when i try to run it , i got this:
Exception in Application constructor
Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class eu.hansolo.spacefx.SpaceFX
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:890)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:802)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	... 1 more
Caused by: MediaException: UNKNOWN : com.sun.media.jfxmedia.MediaException: Could not create player! : com.sun.media.jfxmedia.MediaException: Could not create player!
	at javafx.scene.media.MediaException.exceptionToMediaException(MediaException.java:146)
	at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:518)
	at javafx.scene.media.MediaPlayer.<init>(MediaPlayer.java:421)
	at eu.hansolo.spacefx.SpaceFX.<init>(SpaceFX.java:158)
	... 13 more
Caused by: com.sun.media.jfxmedia.MediaException: Could not create player!
	at com.sun.media.jfxmediaimpl.NativeMediaManager.getPlayer(NativeMediaManager.java:295)
	at com.sun.media.jfxmedia.MediaManager.getPlayer(MediaManager.java:118)
	at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:474)
	... 15 more

**Comment by daniel4git** [comment]
**_at eu.hansolo.spacefx.SpaceFX.(SpaceFX.java:158)_**

**Comment by daniel4git** [comment]
the os is Linux manjaro 4.19.88-1-MANJARO
jdk11

**Comment by HanSolo** [comment]
So I guess you have OpenJDK 11 installed (e.g. adoptopenjdk) in combination with OpenJFX (e.g. from the gluonhq site). It works without any problem on my Ubuntu machine and my Mac.

**Comment by KMUS** [comment]
Same issue here.

Ubuntu 18.04.4 LTS

```
export JAVA_HOME=$(pwd)/tools/jdk-11.0.6+10
export PATH=$PATH:$JAVA_HOME/bin
not needed
export PATH_TO_FX=$(pwd)/tools/javafx-sdk-13.0.2/lib

cd SpaceFX
./gradlew clean run
```

> Caused by: MediaException: UNKNOWN : com.sun.media.jfxmedia.MediaException: Could not create player! : com.sun.media.jfxmedia.MediaException: Could not create player!

This just happens under Linux. Under Windows it works fine.
